# Generated by Django 4.0.6 on 2022-07-18 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(choices=[('Tarjeta', 'TARJETA'), ('Efectivo', 'EFECTIVO')], max_length=8, verbose_name='Forma de pago')),
            ],
        ),
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('tamaño', models.CharField(choices=[('P', 'PEQUEÑO'), ('M', 'MEDIANO'), ('G', 'GRANDE')], max_length=10, verbose_name='Tamaño')),
            ],
            options={
                'verbose_name': 'Pastel',
                'verbose_name_plural': 'Pasteles',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo', models.FloatField(verbose_name='Sueldo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.vendedor', verbose_name='Vemdedor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('pastel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.pastel')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('pastel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.pastel')),
            ],
        ),
        migrations.CreateModel(
            name='JefeProduccion',
            fields=[
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo', models.FloatField(verbose_name='Sueldo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
